### ISSUE TITLE
疑似「Rime 徐码五二顶」翻译长度为三到四的输入段功能失效

### ISSUE THREAD

**Issue by arockshan** [Ace-Who/rime-xuma#2]
### 可以「五二顶」的 [Readme.md](https://github.com/Ace-Who/rime-xuma/blob/master/misc/%E4%BA%94%E4%BA%8C%E9%A1%B6/README.md) 中的 *demo动图*：![徐码五二顶词组demo动图](https://github.com/Ace-Who/rime-xuma/blob/master/misc/%E4%BA%94%E4%BA%8C%E9%A1%B6/demo/xuma_52p_phrase_style.gif) 为对照。

---

## 下面以仅打 `冰灯` 二字为例，说明我的问题

- 在我的 win10 电脑上，当 ***预显*** 设为 **正常预显** 时，

    ```yaml
    - name: xuma_52p_precand  # 在 preedit 中分段提示顶功候选
        states: [ 正常预显, 预显候选 ]
        reset: 0
    ```

    输入 xa → xax → xaxe , 候选样式 分别如下：
    
    ![正常预显xa](https://user-images.githubusercontent.com/62659791/104289820-90060880-54f4-11eb-9a89-31f645a1723f.png)    ![正常预显xax](https://user-images.githubusercontent.com/62659791/104289825-91373580-54f4-11eb-9968-5b573d988293.png)    ![正常预显xaxe](https://user-images.githubusercontent.com/62659791/104289831-9300f900-54f4-11eb-8c35-196e8cac5480.png)

- 当 ***预显*** 设为 **预显候选** 时：

    输入 xa → xax → xaxe ，候选样式 则如下：

    ![预显候选xa](https://user-images.githubusercontent.com/62659791/104289969-b5931200-54f4-11eb-9cd0-c7cb41cddfc5.png)    ![预显候选xax](https://user-images.githubusercontent.com/62659791/104289978-b6c43f00-54f4-11eb-868b-8090f0572b29.png)    ![预显候选xaxe](https://user-images.githubusercontent.com/62659791/104289988-b9bf2f80-54f4-11eb-9a0a-cbd2af08bc5c.png)

    ---

## 我的困惑是

- 选 **正常预显** 时，候选区不能按 "xa x"（冰道） → "xa xe"(冰精) 提示一简字与二简字候选——即当编码超过二码，为三码或四码时，前二码自然地区隔出第一个二简字，且以第三码为第二个简字的第一码来提示第二个简字——而是仍按 "xex"（  ） → "xaxe"(冰灯) 整体提示。

- 选 **预显候选** 时，**候选** 没有改变，但在 **编码区** 已经能同步提示一简字与二简字，可是编码输入区的位置被 **预显** 占了导致无法看到顶字后余下的编码。

- 在您的示例中，仅就 `冰灯` 二字而言，”xa x“ (冰道) → ”xaxe“ (冰灯) 的序列表明方案能自动将  ***长度为三的输入段*** 翻译成 ”二简字 一简字 “的序列，但是我的方案从不这样。

- 当我把 `translator/enable_sentence: false`  改为 `translator/enable_sentence: true` 时，五顶二和五顶四的顶功皆失效，而候选的句子正是 **预显候选**  模式中的预显。样式如下：
        
    ![打句xax](https://user-images.githubusercontent.com/62659791/104294903-c0e93c00-54fa-11eb-972d-0e2213005760.png)     ![打句xaxe](https://user-images.githubusercontent.com/62659791/104294914-c6468680-54fa-11eb-84fa-d75ce2e2a01b.png)    ![打句xaxek](https://user-images.githubusercontent.com/62659791/104294926-cb0b3a80-54fa-11eb-8bdf-4e85044359b6.png)

---

## 附上我对 *xuma_52p_qshare.schema.yaml* 做的更改

（为了方便调整参数，我的自定义文件直接从原方案文件中抄了大量代码，有改动的都以 `# [有更改]` 的注释形式标明。）

```yaml
# xuma_52p_qshare.custom.yaml
# xuma_52p_qshare version: "2020-12-16"
# encoding: utf-8

patch:
  switches:
    - options: [ gb2312, gbk, big5, utf8 ]
      states: [ gb2312, GBK, BIG5, UTF-8 ]
      reset: 1
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      states: [ 漢字, 汉字 ]
    - name: traditionalization
      reset: 0
      states: [ 简体保持, 簡入繁出 ]
    - name: ascii_punct
      states: [ 。，, ．， ]
    - name: xuma_spelling  # [有更改]
      reset: 0
      states: [ 拆, 扌⺁丅丶 ]
    - name: xmsp_hide_pinyin  # [有更改]
      reset: 1
      states: [ 音, 哑 ]
    - name: xuma_postpone_fullcode
      reset: 1
      states: [ ＝原始排序, ↓全码后置 ]
    - name: single_char_only
      states: [ 词组派, 单字派 ]  # [有更改]
      reset: 0
    - name: preedit_lazy_clock
    - name: xuma_52p_precand
      states: [ 正常预显, 预显候选 ]
    - name: detailed_x52_precand

  translator:
    dictionary: xuma_52p
    prism: xuma_52p_qshare
    enable_completion: false
    enable_sentence: false
    enable_user_dict: false
    enable_encoder: false
    encode_commit_history: false
    preedit_format:  # [有更改]
      - xform/$/\t〔主〕/

  # 结合 recognizer，仅翻译长度为三到四的输入段。
  long:
    tag: long
    dictionary: xuma_52p_long
    enable_user_dict: false
    enable_sentence: false
    preedit_format:  # [有更改]
      - xform/$/\t〔长〕/

  make_phrase:
    dictionary: xuma
    user_dict: xuma
    enable_encoder: false  # [有更改]
    enable_user_dict: false  # [有更改]
    enable_sentence: false  # [有更改]
    preedit_format:
      - xform/$/\t〔造词〕/
    tag: make_phrase

  "history/size": 3  # [有更改]

  "style/horizontal": false  # [有更改]
```

---
