### ISSUE TITLE
使用拼音反查时，如何更改为简体优先？

### ISSUE THREAD

**Issue by YakshaChien** [Ace-Who/rime-xuma#3]
请教大佬，使用拼音反查时，默认排序以繁体优先，每次用的时候都要手动切换到简体，不是很方便，请问更改什么设置可以默认设为简体？
我看了一下 `xuma_qshare.schema.yaml`
> \- name: simplification
    states: [ 漢字, 汉字 ]

这个默认就是simplification，不知道如何修改。

**Comment by ywxt** [comment]
states下面加一个项：
reset: 1

**Comment by Ace-Who** [comment]
```yaml
  - name: simplification
    states: [ 漢字, 汉字 ]
    reset: 1
```

目前简化字选项不能区分反查模式和其他模式。
